### ISSUE TITLE
[net6-android] Linker error

### ISSUE THREAD

**Issue by jeromelaban** [dotnet/android#6673]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

VS2022 17.1 Preview 4

### Description

When building an application, the following error appears when `<PublishTrimmed>true</PublishTrimmed>`:

```
31.0.200-preview.12.2\tools\Xamarin.Android.Common.targets(1379,3): error XALNS7002: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
31.0.200-preview.12.2\tools\Xamarin.Android.Common.targets(1379,3): error XALNS7002:    at Mono.Collections.Generic.Collection`1.get_Item(Int32 index) in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Collections.Generic/Collection.cs:line 32
31.0.200-preview.12.2\tools\Xamarin.Android.Common.targets(1379,3): error XALNS7002:    at Mono.Cecil.MetadataReader.ReadExportedTypes() in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil/AssemblyReader.cs:line 2763
31.0.200-preview.12.2\tools\Xamarin.Android.Common.targets(1379,3): error XALNS7002:    at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TRet& variable, TItem item, Func`3 read) in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil/ModuleDefinition.cs:line 989
31.0.200-preview.12.2\tools\Xamarin.Android.Common.targets(1379,3): error XALNS7002:    at Mono.Cecil.ModuleDefinition.get_ExportedTypes() in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil/ModuleDefinition.cs:line 560
31.0.200-preview.12.2\tools\Xamarin.Android.Common.targets(1379,3): error XALNS7002:    at Mono.Cecil.MetadataResolver.GetType(ModuleDefinition module, TypeReference reference) in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil/MetadataResolver.cs:line 153
31.0.200-preview.12.2\tools\Xamarin.Android.Common.targets(1379,3): error XALNS7002:    at Mono.Cecil.TypeReference.Resolve() in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil/TypeReference.cs:line 278
31.0.200-preview.12.2\tools\Xamarin.Android.Common.targets(1379,3): error XALNS7002:    at Java.Interop.Tools.Cecil.TypeDefinitionCache.Resolve(TypeReference typeReference) in /Users/builder/azdo/_work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/TypeDefinitionCache.cs:line 20
31.0.200-preview.12.2\tools\Xamarin.Android.Common.targets(1379,3): error XALNS7002:    at Java.Interop.Tools.Cecil.TypeDefinitionRocks.<GetTypeAndBaseTypes>d__5.MoveNext() in /Users/builder/azdo/_work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/TypeDefinitionRocks.cs:line 40
31.0.200-preview.12.2\tools\Xamarin.Android.Common.targets(1379,3): error XALNS7002:    at Java.Interop.Tools.Cecil.TypeDefinitionRocks.IsSubclassOf(TypeDefinition type, String typeName, IMetadataResolver resolver) in /Users/builder/azdo/_work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/TypeDefinitionRocks.cs:line 94
31.0.200-preview.12.2\tools\Xamarin.Android.Common.targets(1379,3): error XALNS7002:    at MonoDroid.Tuner.FixAbstractMethodsStep.FixAbstractMethods(AssemblyDefinition assembly)
31.0.200-preview.12.2\tools\Xamarin.Android.Common.targets(1379,3): error XALNS7002:    at Xamarin.Android.Tasks.LinkAssembliesNoShrink.RunTask()
31.0.200-preview.12.2\tools\Xamarin.Android.Common.targets(1379,3): error XALNS7002:    at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/builder/azdo/_work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 17
```

### Steps to Reproduce

I do not yet have steps to reproduce, but the similar app with `net6.0-ios` does not fail during the linking.

### Did you find any workaround?

Disable the linker.

**Comment by dellis1972** [comment]
The `LinkAssembliesNoShrink` task suggets this is a `Debug` build? I would think we should not be supporting `PublishTrimmed` in a `Debug` build.

**Comment by jonathanpeppers** [comment]
Might be related to: https://github.com/xamarin/xamarin-android/issues/6628

**Comment by bddckr** [comment]
I have a very similar stack trace when building for Release in my project. I also have no reproduction steps yet, but I am attaching the binlog. The setup is quite involved, but hopefully it can be ignored and the important bits lead to some insight.
[msbuild.zip](https://github.com/xamarin/xamarin-android/files/7959847/msbuild.zip)

**Comment by jeromelaban** [comment]
> The LinkAssembliesNoShrink task suggets this is a Debug build? I would think we should not be supporting PublishTrimmed in a Debug build.

@dellis1972 I think it should be supported, this is particularly important to be able to debug issues related to trimming.
