### ISSUE TITLE
Android SDK Manager + Full List repository is broken

### ISSUE THREAD

**Issue by jonpryor** [dotnet/android#6965]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.), Android for .NET (net6.0-android, etc.)

### Description

Starting sometime during the week of 2022-Apr-18, attempts to use the [**Full List (Unsupported)** repository](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-sdk?tabs=windows#repository-selection) would result in the error message:

> Loading SDK component information failed. Please retry. ❌

<img width="724" alt="image" src="https://user-images.githubusercontent.com/155958/165309287-202bb2c7-aeeb-4918-af20-2f91dc795808.png">

The `InstallAndroidDependencies` target would also fail:

```bash
$ msbuild /t:InstallAndroidDependencies App.csproj
…
…/Xamarin.Installer.Common.targets(12,3): error : Could not parse xamarin android xml. For more info, check the logged manifest file
…/Xamarin.Installer.Common.targets(12,3): error : 'en' is an unexpected token. The expected token is '"' or '''. Line 3, position 12.
…/Xamarin.Installer.Common.targets(12,3): error : Failed to install required Android SDK components. Consider setting $(AndroidDependencyInstallationTimeout) to a value larger than '7' minutes.
…/Xamarin.Installer.Common.targets(12,3): error : Input string was not in a correct format.
…
    4 Error(s)
```

### Steps to Reproduce

1. Open the [Android SDK Manager](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-sdk)
2. Set the [Repository selection](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-sdk?tabs=windows#repository-selection) to **Full List (Unsupported)**
3. When page refreshes, an error message is shown.

### Did you find any workaround?

Use the **Approved List (Recommended)** repository selection.

**Comment by jonpryor** [comment]
See also:

  * https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1528106
  * https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1527425

**Comment by jonpryor** [comment]
See also:

  * https://twitter.com/mzikmunddev/status/1518251124029116418

**Comment by devilwacause** [comment]
Same issue.  VS2017.  Fails regardless if Microsoft or Google selected.

**Comment by timvandenhof** [comment]
Same issue on Visual Studio for Mac: VS for Mac Enterprise 8.10.23 (build 7).

The approved list is working fine, the full list is throwing the following error:
<img width="763" alt="Screenshot 2022-05-11 at 13 18 41" src="https://user-images.githubusercontent.com/2083464/167838937-eba3a2ae-ad1c-4a34-b386-1494c56c0130.png">

I asked a colleague to reproduce this issue on Windows (VS2022 preview), and the error over there seems a little different. Something like 'instance' being 'null'.

This prevents me from switching from Target SDK 30 to 31.

**Comment by devilwacause** [comment]
Any update on this?

**Comment by SarthakB26** [comment]
I am having the same issue with Fresh VS 2022 community install.
Got below issue when try to open both Android SDK manager or Device manager

Xamarin - 17.6.0.251-d17-6+318364c
No Android SDK instance matching the 'C:\Program Files (x86)\Android\android-sdk' path
Failed to download Xamarin Repository manifest from https://aka.ms/xamarin/sdkmanifest/d17-6. System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Xamarin.Installer.AndroidSDK.Manager.Helper.DownloadToString(Uri url, String& output)
   at Xamarin.Installer.AndroidSDK.Repository.LoadManifest()
---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---<---

Trying to load cached manifest...
[AndroidSDK.Discover]: Failure parsing Android manifest: One or more errors occurred.
[AndroidSDK.Discover]: This is usually due to bad XML in one or more of the SDK manifests.
Discovery failed: 
System.ArgumentNullException: Value cannot be null.
Parameter name: instance
   at Xamarin.Installer.AndroidSDK.AndroidSDKInstaller.RefreshState(AndroidSdkInstance instance, Boolean localOnly, Boolean performFullDetection)
   at Xamarin.Installer.AndroidSDK.Manager.AndroidSDKManager.<>c__DisplayClass46_0.<Load>b__0(Task`1 t)
No Android SDK instance matching the 'C:\Program Files (x86)\Android\android-sdk' path

I tried opening https://aka.ms/xamarin/sdkmanifest/d17-6 on my browser and I able to download xml file without any issue
https://aka.ms/xamarin/sdkmanifest/d17-6

Please help If I need to configure proxy setting inside Visual Studio and how

**Comment by SarthakB26** [comment]
@lansalot I was able to install and update required sdk's using android sdkmanager.
here's the doc : https://developer.android.com/tools/sdkmanager.
For emulator I had to download Android Studio. Visual studio detect running emulator even through Android studio and will allow to deploy app on it.

**Comment by lansalot** [comment]
Thanks, am in progress doing that - but for some reason, tho most of it worked fine, the emulator installation failed. Will try it again tho.

**Comment by MagicAndre1981** [comment]
for me it works in VS 2022 17.6 LTSC:

![AndroidSDKManager](https://github.com/xamarin/xamarin-android/assets/8274816/9f9caca1-f22a-4fae-bc69-626cacc8e469)

At time of creating the issue I also had the issue.

**Comment by HannanHan** [comment]
any update on this? both vs2022 & vs2022 preview giving me the same error

**Comment by MagicAndre1981** [comment]
> any update on this? both vs2022 & vs2022 preview giving me the same error

for me it works in 17.8

**Comment by ssuppan** [comment]
I'm getting the same error too.  It really doesn't inspire confidence in using Visual Studio 2022 (for windows) when Visual Studios For Mac is abandoned.  I hate to say it but we are considering other tools.

**Comment by DeerSteak** [comment]
This is also broken when trying to install android dependencies using the instructions for the .NET MAUI extension for VS Code on macOS 14.4.1, whether using a separate Terminal window or the one built into Code.

**Comment by MagicAndre1981** [comment]
works for me now, so it can be closed:

<img width="1868" height="790" alt="Image" src="https://github.com/user-attachments/assets/539d0c6c-4fc7-407e-b6c5-3e23e83320f4" />
