### ISSUE TITLE
JAVA0000 + java.lang.IllegalStateException when installing an app

### ISSUE THREAD

**Issue by jonpryor** [dotnet/android#7348]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.), Android for .NET (net6.0-android, etc.)

### Affected platform version

main

### Description

"Random"/occasional error when running the `Install` target, e.g. [on CI](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6652312&view=ms.vss-test-web.build-test-results-tab&runId=53097356&resultId=100054&paneView=attachments) for the [`MonoAndroidExportReferencedAppStarts(True,"",True)` unit test](https://github.com/xamarin/xamarin-android/blob/39183370b98b3afaa0211c8c61de923bde537941/tests/MSBuildDeviceIntegration/Tests/MonoAndroidExportTest.cs#L47-L133):

```
Task "InstallApkSet"
  …
  /Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.16-101/x64/Contents/Home/bin/java -Xmx1G -jar /Users/runner/work/1/s/xamarin-android/bin/Release/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.0-ci.pr.gh7342.159/tools/bundletool.jar install-apks --apks obj/Release/android/bin/x_com.xamarin.monoandroidexportreferencedappstarts.apks --adb /Users/runner/Library/Android/sdk/platform-tools/adb --allow-downgrade --modules _ALL_
  error: Error retrieving device SDK version. Please try again.
  java error JAVA0000: java.lang.IllegalStateException
  java error JAVA0000:  Error retrieving device SDK version. Please try again.
  java error JAVA0000: 	at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
  java error JAVA0000: 	at com.android.tools.build.bundletool.device.DeviceAnalyzer.getDeviceSpec(DeviceAnalyzer.java:57)
  java error JAVA0000: 	at com.android.tools.build.bundletool.commands.InstallApksCommand.execute(InstallApksCommand.java:185)
  java error JAVA0000: 	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:91)
  java error JAVA0000: 	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:49)
```

Only this one test failed, so it seems unlikely that the Android emulator is "bad".

Should we check for `Please try again` and re-run the `bundletool.jar` invocation on failure?

### Steps to Reproduce

Happens randomly.  No reproduction steps.

**Comment by dellis1972** [comment]
This might be tricky as the `InstallApkSet` task at the end of the day uses `ToolTask` to execute the command. 
We might be able to hack around this , perhaps when we are just on CI maybe? via a `AndroidRetryInstall` property or something ...
