### ISSUE TITLE
Update API doc generation and mdoc conversion to use net8.0

### ISSUE THREAD

**Issue by pjcollins** [dotnet/android#7974]
Context: https://github.com/xamarin/xamarin-android/pull/7958#issuecomment-1511892550

We should update our targets and pipelines related to API doc generation to use .NET instead of mono.

**Comment by jpobst** [comment]
Note that there are 2 parts here:

1. Generate the XML documentation from the `net7.0-android33.0` `Mono.Android.dll` instead of the `monoandroid10` `Mono.Android.dll`.
2. Use .NET instead of Mono to run tools such as `MDoc`.

(1) is blocking us from removing `monoandroid10` `Mono.Android.dll` so it is the more immediate concern.

However, it may make sense to do both parts at the same time.  🤷‍♂️

**Comment by pjcollins** [comment]
Part 1 should be fixed by https://github.com/xamarin/xamarin-android/pull/8007. We can look at updating to a version of mdoc that supports net6.0 (https://github.com/mono/api-doc-tools/pull/639) in a future PR.

**Comment by pjcollins** [comment]
Part 2 is hitting an issue during the update that requires further investigation:

         Updating: Android.Icu.Lang.UCharacter
         mdoc: Mono.Documentation.MDocAssemblyException: Error processing Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065 from obj/docs-gen-temp/xamarin-android-sdk-13/Mono.Android.dll
          ---> System.ArgumentException: The surrogate pair (0xDBFF, 0x3B) is invalid. A high surrogate character (0xD800 - 0xDBFF) must always be paired with a low surrogate character (0xDC00 - 0xDFFF).
            at System.Xml.XmlTextEncoder.WriteSurrogateChar(Char lowChar, Char highChar)
            at System.Xml.XmlTextEncoder.Write(String text)
            at System.Xml.XmlTextWriter.WriteString(String text)
            at System.Xml.XmlAttribute.WriteContentTo(XmlWriter w)
            at System.Xml.XmlAttribute.WriteTo(XmlWriter w)
            at System.Xml.XmlElement.WriteStartElement(XmlWriter w)
            at System.Xml.XmlElement.WriteElementTo(XmlWriter writer, XmlElement el)
            at Mono.Documentation.MDocUpdater.WriteXml(XmlElement element, TextWriter output) in /Users/runner/work/1/s/mdoc/Mono.Documentation/MDocUpdater.cs:line 584
            at Mono.Documentation.MDocUpdater.<>c__DisplayClass75_0.<WriteFile>b__0(String file) in /Users/runner/work/1/s/mdoc/Mono.Documentation/MDocUpdater.cs:line 593
            at Mono.Documentation.MdocFile.UpdateFile(String file, Action`1 creator) in /Users/runner/work/1/s/mdoc/Mono.Documentation/MdocFile.cs:line 63
            at Mono.Documentation.MDocUpdater.DoUpdateType2(String message, XmlDocument basefile, TypeDefinition type, FrameworkTypeEntry typeEntry, String output, Boolean insertSince) in /Users/runner/work/1/s/mdoc/Mono.Documentation/MDocUpdater.cs:line 1824
            at Mono.Documentation.MDocUpdater.DoUpdateType(AssemblySet set, AssemblyDefinition assembly, TypeDefinition type, FrameworkTypeEntry typeEntry, String basepath, String dest) in /Users/runner/work/1/s/mdoc/Mono.Documentation/MDocUpdater.cs:line 922
            at Mono.Documentation.MDocUpdater.DoUpdateAssembly(AssemblySet assemblySet, AssemblyDefinition assembly, XmlElement index_types, String source, String dest, HashSet`1 goodfiles) in /Users/runner/work/1/s/mdoc/Mono.Documentation/MDocUpdater.cs:line 1135
            at Mono.Documentation.MDocUpdater.DoUpdateAssemblies(String source, String dest) in /Users/runner/work/1/s/mdoc/Mono.Documentation/MDocUpdater.cs:line 1078
            --- End of inner exception stack trace ---
            at Mono.Documentation.MDocUpdater.DoUpdateAssemblies(String source, String dest) in /Users/runner/work/1/s/mdoc/Mono.Documentation/MDocUpdater.cs:line 1085
            at Mono.Documentation.MDocUpdater.Run(IEnumerable`1 args) in /Users/runner/work/1/s/mdoc/Mono.Documentation/MDocUpdater.cs:line 467
            at Mono.Documentation.MDoc.Run(String[] args) in /Users/runner/work/1/s/mdoc/Mono.Documentation/mdoc.cs:line 82
            at Mono.Documentation.MDoc.Main(String[] args) in /Users/runner/work/1/s/mdoc/Mono.Documentation/mdoc.cs:line 20

**Comment by pjcollins** [comment]
@dotnet-policy-service  help

**Comment by pjcollins** [comment]
Seems like this is working now.
