### ISSUE TITLE
WebSocket exception with LLVM and full AOT Enabled in .NET Android App

### ISSUE THREAD

**Issue by kcrg** [dotnet/android#9083]
### Android framework version

net8.0-android, net9.0-android

### Affected platform version

VS 17.11 Preview and 17.10 Stable, .NET 8.0.6 and .NET 9.0.0-preview.5.24306.8

### Description

I am encountering an issue with WebSocket functionality in a .NET Android application when LLVM and full AOT is enabled. The application fails to establish WebSocket connections.

**Configuration:**
```xml
<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-android|AnyCPU'">
  <EnableLLVM>True</EnableLLVM>
  <AndroidEnableProfiledAot>False</AndroidEnableProfiledAot>
  <RunAOTCompilation>True</RunAOTCompilation>
</PropertyGroup>
```

When running the application with the above configuration, WebSocket connections throws exception. The same code works without issues when LLVM is disabled.

**Expected Behavior:**
The WebSocket connection should be established, messages should be sent and received without errors, and the connection should be properly closed.

**Actual Behavior:**
WebSocket connection throws exception when LLVM is enabled with the above configuration.

**Stack Trace:**
```
Message: net_webstatus_ConnectFailure
StackTrace: at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri , HttpMessageInvoker , CancellationToken , ClientWebSocketOptions )
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri , HttpMessageInvoker , CancellationToken )
   at WebsocketLLVMIssue.WebSocketClient.ConnectAsync(String uri)
   at WebsocketLLVMIssue.MainActivity.ConnectAsync()
```

**Additional Notes:**
- Disabling LLVM resolves the issue, indicating a potential conflict between WebSocket operations and LLVM optimizations.
- A repro project is attached to this issue for further investigation.

### Steps to Reproduce

1. Create a new .NET Android project.
2. Implement WebSocket client functionality.
3. Add UI elements for connecting, sending messages, and disconnecting.
4. Handle user interactions to manage WebSocket operations.
5. Configure the project to use LLVM without AOT.
6. Build and run the project on an Android device or emulator.
7. Observe the behavior when trying to connect using WebSocket.

Or download this minimal project: [WebsocketLLVMIssue.zip](https://github.com/user-attachments/files/16118093/WebsocketLLVMIssue.zip)

### Did you find any workaround?

nope

**Comment by grendello** [comment]
@kcrg Could you please collect more info for us by issuing the following commands from the VS Developer Prompt:

```cmd
> adb shell debug.mono.log default,assembly,mono_log_level=debug,mono_log_mask=all
> adb logcat -G 65M
> adb logcat -c
rem Start the crashing application here, wait for it to crash, then wait 5 more seconds and...
> adb logcat -d > logcat.txt
```

Then attach the resulting `logcat.txt` file to this issue, thanks!

**Comment by kcrg** [comment]
@grendello Done, I just added the logcat.txt to the issue

**Comment by grendello** [comment]
> @grendello Done, I just added the logcat.txt to the issue. I had problem with `adb shell debug.mono.log default,assembly,mono_log_level=debug,mono_log_mask=all` it returns `/system/bin/sh: debug.mono.log: inaccessible or not found`

Oops, my bad, sorry about that. The first command should be:

```cmd
> adb shell setprop debug.mono.log default,assembly,mono_log_level=debug,mono_log_mask=all
```

And please attach `logcat.txt` directly here, to your next comment, thanks!

**Comment by kcrg** [comment]
@grendello Here it is: [logcat.txt](https://github.com/user-attachments/files/16129110/logcat.txt)

**Comment by grendello** [comment]
@kcrg it looks like a runtime issue, I can't find anything that's specific to .NET for Android.  @steveisok I don't have permissions to transfer this to `dotnet/runtime`, would you mind doing that and assigning somebody to take a look at this? Thanks!
