### ISSUE TITLE
Android: Cannot deploy & debug on physical device (Android 12) with VS4Mac

### ISSUE THREAD

**Issue by MSicc** [dotnet/android#9261]
### Description

I am not able to debug any Android App on device with .NET MAUI (latest workload 7.0.92);

Something is getting deployed to the device, but never starts. Starting manually results in an immediate crash.
The deployment task hangs like forever at:

```
Target _Upload:
    Using cached value from RegisterTaskObject
    Found device: N0AA003638K50600016
```

Every now and then it gets past that point, then I see a bunch of these errors:

```
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/tools/Xamarin.Android.Common.Debugging.targets(676,5): error ADB1000: Mono.AndroidTools.AdbException: Attempted to read past the end of the stream.
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/tools/Xamarin.Android.Common.Debugging.targets(676,5): error ADB1000:  ---> System.IO.EndOfStreamException: Attempted to read past the end of the stream.
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/tools/Xamarin.Android.Common.Debugging.targets(676,5): error ADB1000:    at Mono.AndroidTools.Util.ReadFullAsyncResult.EndRead(IAsyncResult ar) in /Users/runner/work/1/s/xamarin-android/external/monodroid/tools/msbuild/external/androidtools/Mono.AndroidTools/Util/StreamExtensions.cs:line 93
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/tools/Xamarin.Android.Common.Debugging.targets(676,5): error ADB1000:    at Mono.AndroidTools.Adb.AdbSyncClient.FileWrite_OnReadStatus(IAsyncResult ar) in /Users/runner/work/1/s/xamarin-android/external/monodroid/tools/msbuild/external/androidtools/Mono.AndroidTools/Adb/AdbSyncClient.cs:line 619
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/tools/Xamarin.Android.Common.Debugging.targets(676,5): error ADB1000:    --- End of inner exception stack trace ---
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/tools/Xamarin.Android.Common.Debugging.targets(676,5): error ADB1000:    at Mono.AndroidTools.Util.AggregateAsyncResult.CheckError(CancellationToken token) in /Users/runner/work/1/s/xamarin-android/external/monodroid/tools/msbuild/external/androidtools/Mono.AndroidTools/Util/AggregateAsyncResult.cs:line 70
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/tools/Xamarin.Android.Common.Debugging.targets(676,5): error ADB1000:    at Mono.AndroidTools.Adb.AdbSyncClient.EndPush(IAsyncResult result) in /Users/runner/work/1/s/xamarin-android/external/monodroid/tools/msbuild/external/androidtools/Mono.AndroidTools/Adb/AdbSyncClient.cs:line 770
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/tools/Xamarin.Android.Common.Debugging.targets(676,5): error ADB1000:    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/tools/Xamarin.Android.Common.Debugging.targets(676,5): error ADB1000: --- End of stack trace from previous location ---
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/tools/Xamarin.Android.Common.Debugging.targets(676,5): error ADB1000:    at AndroidDeviceExtensions.PushAndInstallPackageAsync(AndroidDevice device, PushAndInstallCommand command, CancellationToken token) in /Users/runner/work/1/s/xamarin-android/external/monodroid/tools/msbuild/external/androidtools/Xamarin.AndroidTools/Devices/AndroidDeviceExtensions.cs:line 198
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/tools/Xamarin.Android.Common.Debugging.targets(676,5): error ADB1000:    at AndroidDeviceExtensions.PushAndInstallPackageAsync(AndroidDevice device, PushAndInstallCommand command, CancellationToken token) in /Users/runner/work/1/s/xamarin-android/external/monodroid/tools/msbuild/external/androidtools/Xamarin.AndroidTools/Devices/AndroidDeviceExtensions.cs:line 223
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/tools/Xamarin.Android.Common.Debugging.targets(676,5): error ADB1000:    at Xamarin.Android.Tasks.FastDeploy.InstallPackage(Boolean installed) in /Users/runner/work/1/s/xamarin-android/external/monodroid/tools/msbuild/Tasks/FastDeploy.cs:line 353
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/tools/Xamarin.Android.Common.Debugging.targets(676,5): error ADB1000:    at Xamarin.Android.Tasks.FastDeploy.InstallPackage(Boolean installed) in /Users/runner/work/1/s/xamarin-android/external/monodroid/tools/msbuild/Tasks/FastDeploy.cs:line 370
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/tools/Xamarin.Android.Common.Debugging.targets(676,5): error ADB1000:    at Xamarin.Android.Tasks.FastDeploy.RunTaskAsync() in /Users/runner/work/1/s/xamarin-android/external/monodroid/tools/msbuild/Tasks/FastDeploy.cs:line 216
```

Deploying a Xamarin.Forms app works without any problems!
Deploying to the default Pixel 5 Android API 33 emulator works as well.

### Steps to Reproduce

Create a new .NET MAUI App
Hit the Debug button

Expected outcome: App gets deployed and debugging starts
Actual outcome: Something gets deployed,  but most of the time the process gets stuck. If it gets past that step, the above mentioned error is written multiple times in the output window.

### Link to public reproduction project repository

-

### Version with bug

Unknown/Other

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12 (unsure about others).

### Did you find any workaround?

No

**Comment by jonathanpeppers** [comment]
Can you confirm if this is still an issue using VS Code or CLI and our latest .NET 9 release? Thanks!
* https://github.com/dotnet/android/releases/tag/35.0.78

**Comment by MSicc** [comment]
Well from my part this can be closed - I am not using Android anymore.

If you are one of the other commenters and still having this issue, you should probably jump back in and test (and report back).

**Comment by beeradmoore** [comment]
Not using VSCode so I can't comment on if it is working. My suggested workaround was for VS4Mac/Rider.

When I get time I can try opening my MAUI project in VSCode and see if it deploys ok or not.

To keep/put extra info out there Rider wants to start adb even when I am working on a .NET console project because it does it no matter what project you open. I think this is dumb so I changed my settings there to not start adb with Rider and instead if I want adb I manually run `adb-server` in my `.zprofile` which is similar to that `android_wireless` I mentioned earlier.

```
adb-server()
{
    adb kill-server
    adb -P 5037 nodaemon server 
}
```
